#!/usr/bin/env bash
# change nginx server to listen on port 80 and restart
apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
