#!/usr/bin/env bash
# script of task 0 but fix the nginx server but in a better way
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
