#!/usr/bin/env bash
# print to infenity and beyond but when recinving sigterm
# print I am invincible!!!

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
echo "To infinity and beyond"
sleep 2
done
