#!/usr/bin/env bash
# print numbers till 100 if mul by 3 fizz
# if mul by 5 buzz if both fizzbuzz

i=1
while [ $i -le 100 ]
do
	if [ $((i%15)) = 0 ]
        then
                echo "FizzBuzz"
	elif [ $((i%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((i%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	(( i++ ))
done
