#!/usr/bin/env bash
# print 1 to 20 except in 4 & 9 & 17

i=0
while [ $i -lt 21 ]
do
case $i in
4) echo $i
echo "bad luck from China"
;;
9) echo $i
echo "bad luck from Japan"
;;
17) echo $i
echo "bad luck from Italy"
;;
*)
echo $i
esac
(( i++ ))
done
