#!/usr/bin/env bash
# a loop that displays the clock in hours and min.

hour=0
while [ $hour -le 12 ]
do
echo "Hour: $hour"
min=1
while [ $min -le 59 ]
do
echo $min
(( min++ ))
done
(( hour++ ))
done
